# Generated by Django 3.2 on 2022-05-28 01:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gnosis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Element',
            new_name='Topic',
        ),
        migrations.RenameField(
            model_name='elementmorph',
            old_name='element',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='elementnote',
            old_name='element',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='element',
            new_name='topic',
        ),
    ]
