# Generated by Django 3.2 on 2022-05-28 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gnosis', '0002_auto_20220528_0255'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ElementMorph',
            new_name='TopicMorph',
        ),
        migrations.RenameModel(
            old_name='ElementNote',
            new_name='TopicNote',
        ),
        migrations.RenameModel(
            old_name='ElementRelation',
            new_name='TopicRelation',
        ),
    ]
