# Generated by Django 3.2 on 2023-01-21 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnosis', '0003_auto_20220528_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='morph',
            name='summary',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='topic',
            name='summary',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
